//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DatPhong
    {
        public int IDDP { get; set; }
        public int IDKH { get; set; }
        public Nullable<System.DateTime> NGAYDATPHONG { get; set; }
        public Nullable<System.DateTime> NGAYTRAPHONG { get; set; }
        public Nullable<double> SOTIEN { get; set; }
        public Nullable<int> SONGUOIO { get; set; }
        public int IDUSER { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public Nullable<bool> THEODOAN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
    }
}
