//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LoaiPhong
    {
        public int IDLOAIPHONG { get; set; }
        public string TENLOAIPHONG { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<int> SONGUOI { get; set; }
        public Nullable<int> SOGIUONG { get; set; }
        public Nullable<bool> DISABLED { get; set; }
    }
}
